### ISSUE TITLE
typo, idea, bug commands not work.

### ISSUE THREAD

**Issue by CryAngel1970** [tbamud/tbamud#96] opened 2020-09-04 11:44 UTC
I downloaded the released file and checked it.

Typing typo, idea, bug command shuts down the server.

Files necessary for typo, idea, and bug commands exist in the lib/misc folder.
lib/misc/
bugs
ideas
typos
xnames

I didn't know how to debug, so I checked it by putting a log line by line.
An error occurs in the ACMD (do_ibt) function in the ibt.c file.

first_ibt = get_first_ibt(subcmd); There seems to be a problem with
It seems that get_first_ibt is not working.

**Comment by OpieDelivers** [comment] 2020-09-04 13:17
Can you provide the OS you tested this on? (Linux, Windows, etc.)

Check if boards are working as well when you type. Wondering if this may potentially be a permissions issue.

**Comment by CryAngel1970** [comment] 2020-09-04 13:34
I just tested the bulletin board and it works fine.

I'm using Windows 10 and compiled with msvs 2019.

**Comment by OpieDelivers** [comment] 2020-09-04 13:50
@welcor @wyld-sw Any idea what this could be? I'm away for a while.

**Comment by krinosx** [comment] 2020-09-04 17:55
Hi guys,

I just build the most recent code in Windows 10, using Visual Studio 2017.

I am trying to reproduce the problem but I had no success. The Idea, typo
and but appears to be working fine.

Check the screenshot below
[image: image.png].


I will try to update my visual studio to 2019 and check if it introduces
the bug.

Can you check which version of Windows SDK are you using?
[image: image.png]

Kind regards
Giuliano Bortolassi

**Comment by CryAngel1970** [comment] 2020-09-04 18:59
Windows SDK : 10.0.18362.0

Character Set : Use Multi-Byte character Set

[Please refer to tbamud.com for the capture screen.](https://tbamud.com/forum/2-general/5151-does-the-typo-idea-bug-commands-work#9457)


Typing typo in the game ends the program.

**Comment by CryAngel1970** [comment] 2020-09-04 19:31
I just switched to Windows SDK: 10.0.17763.0 and compiled it, but the program still ended.

I compiled it into the tbamud-2020.zip version on the TbaMud Google Drive, but the program ends.

**Comment by krinosx** [comment] 2020-09-04 19:56
Well, I am downloading the MSVC 2019 and will give it a try.

Unfortunately I will not be able to reproduce the Corean windows build. I
dont know if it is something related to the character encoding, so it may
help if you are able to debug.

I can share with you some advice on how to set up Visual Studio to Debug
the tbamud-2020 (check below).


Try to configure and start the debugger, it will help you (and us) to
understand the problem.

*DEBUG SETUP FOR VSCODE - tbamud2020.zip*

The only thing you need to do is to copy the LIB and conf folder to a
folder above the Debug folder.
Check the Screenshot:


[image: image.png]
Kind regards
Giuliano Bortolassi

ps. I will post some updates as soon as I am able to build it with MS
Visual Studio 2019.,

**Comment by CryAngel1970** [comment] 2020-09-05 00:31
Thanks for the reply.
I compiled and tested the original and localized version as you told me.
The original worked fine.
The Korean version causes an error during debugging.
[error screen](https://tbamud.com/forum/2-general/5151-does-the-typo-idea-bug-commands-work#9473)

During debugging, the program did not run due to errors, but when compiled and executed, it worked until the typo command was entered.

There seems to be something wrong with the Hangul input code learned on the Internet.

**Comment by krinosx** [comment] 2020-09-05 01:45
Thank you for sharing the experience you had!! 
It will help future developers/mud admins that may face the same problem.

As I told, I am not able to reproduce the Korean input code (the Hangul). 

Anyway, If you want to dig deeper in the root cause, I suggest you to investigate the telnet protocol files for tbamud (protocol.h/protocol.c).  
MAYBE some special character used in Hangul input code may conflict with the telnet special bytes and it may cause some error in the command parser (skipping a parameter like you said). 

If it was me, I will start resolving that assertion problem. If I am not mistaken the assertion message (sctype.cpp):  

`Expression: c >= -1 && c <= 255`

is related with some byte conversion operation. I imagine that in some point your code will try to assign a value greater than 255 or lesser than 0 yo a byte. I suspect it occurs in the socket reading/writing routine. It may be caused because the Hangul use multi byte characters and the current code may be not prepared to deal with it.

Now that you can debug, if you are able to find the root cause, please share with us!!

Thanks!!

Kind Regards!
Giuliano Bortolassi

**Comment by CryAngel1970** [comment] 2020-09-05 05:09
I faced the assertion message (sctype.cpp) and searched the internet for a workaround but couldn't find it.
`Expression: c >= -1 && c <= 255`

I am still doing novice programming.

I changed the part where the error occurred at first to another source, but the same error occurred and I cannot proceed.
If I compile in release mode, not debug mode, the server can run, but still typing the typo command crashes the server.

Since Hangul is multibyte, there seems to be a problem when reading and writing files.
There will be many other countries that use multibyte rather than Korean, but I couldn't find a solution.

I changed the encoding of all sources to UTF8, but I got countless errors, so I changed the encoding of the sources back to ANSI949. ANSI 949 is a Korean encoding.

Thanks again for the kind response.

**Comment by CryAngel1970** [comment] 2020-09-05 08:31
I just figured out the cause and fixed it.

I don't know why, but it was due to the setting of screen.h.
I don't know if it's the client's problem.

I changed the Annecy code starting with Q to K.
QYEL --> KYEL
QNRM -->  KNRM

Now, typing the typo command does not shut down the server and prints a message.

**Comment by welcor** [comment] 2020-09-09 22:48
ok, since debugging has brought you nowhere, you'll probably need to do this the hard, tiring way - using log statements.
In your ibt.c file, add statements like log("1"); log("2"); etc so you can see where it fails.

Then get back to us with the actual line that's failing.

**Comment by krinosx** [comment] 2020-09-09 23:13
Hi Thomas,

I think Youn Wan-Shik solved the problem. It was related to Annecy code. As
he/she stated in the last email:

"... I just figured out the cause and fixed it.

I don't know why, but it was due to the setting of screen.h.
I don't know if it's the client's problem.

I changed the Annecy code starting with Q to K.
QYEL --> KYEL
QNRM --> KNRM

Now, typing the typo command does not shut down the server and prints a
message. ..."

**Comment by CryAngel1970** [comment] 2020-09-10 05:58
I am grateful to all the people who are interested in my writing and have pondered it together.
This article was written on the tbamud.com forum, but it hasn't been resolved yet, so I'll write it here as well.

I finally found where the error occurs.

The error occurred in the command_interpreter function in the interpreter.c file.

I modified the last of the command_interpreter function to look like this:
When the error is corrected, it must be reverted to the original.
`send_to_char(ch, "Commands Error!\r\n");
//    ((*complete_cmd_info[cmd].command_pointer) (ch, line, cmd, complete_cmd_info[cmd].subcmd));`

Then, I modified it to show what arg and line return.
`line = any_one_arg(argument, arg);`

Add the following to the next line.
This was used to find the cause of the error. To see how the arguments I entered work.
`send_to_char(ch, "arg: %s   line: %s\r\n", arg, line);`

If I type
`aa dd ddd typo`

I will get the following results.
`500H 100M 82V (news) (motd) > arg: aa   line:  dd ddd typo`

In the case of Hangul, it is natural to change the order of commands.
The current English version of typo usage is as follows.
`typo submit <header>`
In the case of <header>, a string containing spaces can be used.

However, in the case of Hangul, it is natural to change the order of commands as follows.
`submit <header> typo`
Basic instruction comes last, auxiliary instruction comes first.

Also, since Hangul uses double-byte characters, it is not possible to determine if it is Hangul using isalpha().

So add the following at the end of the utils.h file.
`#define ishan(ch) (((ch) & 0xE0) > 0x90)
#define ishanasc(ch) (isascii(ch) || ishan(ch))
#define ishanalp(ch) (isalpha(ch) || ishan(ch))
#define isnhdigit(ch) (!ishan(ch) && isdigit(ch))
#define isnhspace(ch) (!ishan(ch) && isspace(ch))`

`static int _parse_name(char *arg, char *name) {
  int i;
  skip_spaces(&arg);
  for (i = 0; (*name = *arg); arg++, i++, name++)
    if (!isalpha(*arg))
      return (1);
  if (!i)
    return (1);
  return (0);}`

Change the code above as below.
Hangul is not read 1byte at a time like the English alphabet, and only 2bytes are read to complete Hangul characters.
`static int _parse_name(char *arg, char *name){
  int i;
  //skip_spaces(&arg);
  for (; isnhspace(*arg); arg++);
  for (i = 0; (*name = *arg); arg++, i++, name++)
    //if (!isalpha(*arg)) 
	if (!ishanalp(*arg))
      return (1);
  if (!i)
    return (1);
  return (0);}`

Also, the void skip_spaces(char **string) function must be modified as follows to use Korean.
`// for (; **string && **string != '\t' && isspace(**string); (*string)++);
for (; **string && isnhspace(**string); (*string)++);`

Finally, you need to change the order of commands in command_interpreter.
I don't know if this is the right way.
This is how I found it out by searching the Internet.
`void command_interpreter(struct char_data *ch, char *argument) {
int cmd, length;
char *line;
char arg[MAX_INPUT_LENGTH];
// Change commands to Hangul word order
char hanparse[MAX_INPUT_LENGTH];
char hancommand[MAX_INPUT_LENGTH];

REMOVE_BIT_AR(AFF_FLAGS(ch), AFF_HIDE);

/* just drop to next line for hitting CR */
skip_spaces(&argument);
if (!*argument)
return;

// Change commands to Korean word order
sprintf(hanparse, "%s", argument);
if(strrchr(hanparse, ' ')) {
sprintf(hancommand, "%s ", strrchr(hanparse, ' '));
hanparse[strlen(hanparse) - (strlen(hancommand) - 1)] = '\0';
strcat(hancommand, hanparse);
argument = hancommand;
} else
argument = hanparse;

skip_spaces(&argument);

/* special case to handle one-character, non-alphanumeric commands; requested
* by many people so "'hi" or ";godnet test" is possible. Patch sent by Eric
* Green and Stefan Wasilewski. */
// Change not to skip Hangul
if (!ishanalp(*argument)) {
// if (!isalpha(*argument)) {
arg[0] = argument[0];
arg[1] = '\0';
line = argument + 1;
} else
line = any_one_arg(argument, arg);`

It is true that errors occur in this function, but I need to correct it because of my weak program skills.
The commands entered are not English, and similar Korean commands should be printed even if they are Korean.

Of course, most commands have been changed to Korean.

We've figured out why and where the error occurred, but the error still persists.

**Comment by welcor** [comment] 2020-09-10 19:08
for what it's worth, it is shown correctly on the forum. You either need to use the <> block in the github editor or write markdown directly (that is, use ` ` ` before and after code blocks):

```
this is code
more code
```

no longer code

**Comment by CryAngel1970** [comment] 2020-09-10 23:11
When I paste multiple lines of code it doesn't seem to work well.

**Comment by welcor** [comment] 2020-11-18 21:12
The bug has been solved on the forums. Closing this.

**Closed by welcor** 2020-11-18 21:12 UTC
